---
- name: Update apt cache # apt-get update
  apt:
    update_cache: yes

- name: Install required packages for Docker # apt-get install apt-transport-https ca-certificates curl software-properties-common
  apt:
    name: "{{ item }}"
    install_recommends: "yes"
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"

- name: Docker - download install script
  get_url:
    url: "https://get.docker.com/"
    dest: "/tmp/install.sh"

- name: Docker - chmod script
  command: "chmod +x /tmp/install.sh"

- name: Docker - install
  command: "/tmp/install.sh"